### PR TITLE
Update my profile for 2024

### PR DESCRIPTION
**Pull request by mdiluz**
* New Frontier job
* Some new skills
* Add a few more socials

I've have noticed that the Vue `timeframe` sorting on the site seems off -  my Feral jobs seem to be out of order. I didn't have time tonight to dig into why though, maybe I'll send up a PR to get that fixed tomorrow.

### CODE REVIEW

**Comment by mdiluz** [comment]
Noticed a few more things worth updating, I'll get those sorted before we merge. marking as draft.

**Comment by mdiluz** [comment]
Alright that's good, thanks for the reminder this needed updating :)

**Review by maybeanerd — APPROVED** [review]
Looking good!
And I see you got mdiluz.io, sweet 👌🏻

I'll create an issue for the timeframe sorting so we don't forget it 😲

**Comment by maybeanerd** [comment]
Here's the issue i created for the bug 👀
https://github.com/maybeanerd/diluz.io/issues/394

**Comment by mdiluz** [comment]
> Looking good! And I see you got mdiluz.io, sweet 👌🏻
Yeah, I've been wanting to set that up for ages. Your prompt here reminded me to shift the blog over and actually use the domain.

**Pull request merged**
